//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoPhan
    {
        public BoPhan()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int ID { get; set; }
        public string TenBP { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
