//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonThu
    {
        public int ID { get; set; }
        public Nullable<int> idHoaDonThu { get; set; }
        public Nullable<int> idBangThuePhong { get; set; }
    
        public virtual BangThuePhong BangThuePhong { get; set; }
        public virtual HoaDonThu HoaDonThu { get; set; }
    }
}
