//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSoVatChat
    {
        public CoSoVatChat()
        {
            this.PhongVatTus = new HashSet<PhongVatTu>();
        }
    
        public string ID { get; set; }
        public string TenCSVC { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public Nullable<decimal> GiaBoiThuong { get; set; }
        public int idTinhTrangPhong { get; set; }
    
        public virtual TinhTrangPhong TinhTrangPhong { get; set; }
        public virtual ICollection<PhongVatTu> PhongVatTus { get; set; }
    }
}
