//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoiVien
    {
        public HoiVien()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<int> RollHV { get; set; }
    
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
