//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.BangThuePhongs = new HashSet<BangThuePhong>();
            this.HoaDonThus = new HashSet<HoaDonThu>();
            this.NguoiOCungs = new HashSet<NguoiOCung>();
        }
    
        public string ID { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public string QuocTich { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<BangThuePhong> BangThuePhongs { get; set; }
        public virtual ICollection<HoaDonThu> HoaDonThus { get; set; }
        public virtual ICollection<NguoiOCung> NguoiOCungs { get; set; }
        public virtual HoiVien HoiVien { get; set; }
    }
}
