//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhong
    {
        public LoaiPhong()
        {
            this.Phongs = new HashSet<Phong>();
        }
    
        public int ID { get; set; }
        public string TenLP { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> TienPhuThu { get; set; }
        public Nullable<int> SoGiuong { get; set; }
        public Nullable<int> SoNguoiToiDaTrenGiuong { get; set; }
    
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
