//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.BangLuongs = new HashSet<BangLuong>();
            this.HoaDonChis = new HashSet<HoaDonChi>();
            this.HoaDonThus = new HashSet<HoaDonThu>();
            this.UserS = new HashSet<User>();
        }
    
        public string ID { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public int IDChucDanh { get; set; }
        public int IDBoPhan { get; set; }
    
        public virtual ICollection<BangLuong> BangLuongs { get; set; }
        public virtual BoPhan BoPhan { get; set; }
        public virtual ChucDanh ChucDanh { get; set; }
        public virtual ICollection<HoaDonChi> HoaDonChis { get; set; }
        public virtual ICollection<HoaDonThu> HoaDonThus { get; set; }
        public virtual ICollection<User> UserS { get; set; }
    }
}
