//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.BangThuePhongs = new HashSet<BangThuePhong>();
            this.PhongVatTus = new HashSet<PhongVatTu>();
        }
    
        public string ID { get; set; }
        public string TenP { get; set; }
        public int idLoaiPhong { get; set; }
        public int idTinhTrangPhong { get; set; }
    
        public virtual ICollection<BangThuePhong> BangThuePhongs { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual TinhTrangPhong TinhTrangPhong { get; set; }
        public virtual ICollection<PhongVatTu> PhongVatTus { get; set; }
    }
}
