//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongVatTu
    {
        public int ID { get; set; }
        public string idPhong { get; set; }
        public string idCoSoVatChat { get; set; }
    
        public virtual CoSoVatChat CoSoVatChat { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
