//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KHACHSANEntities : DbContext
    {
        public KHACHSANEntities()
            : base("name=KHACHSANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BangLuong> BangLuongs { get; set; }
        public DbSet<BangThuePhong> BangThuePhongs { get; set; }
        public DbSet<BoPhan> BoPhans { get; set; }
        public DbSet<ChiTietHoaDonThu> ChiTietHoaDonThus { get; set; }
        public DbSet<ChucDanh> ChucDanhs { get; set; }
        public DbSet<CoSoVatChat> CoSoVatChats { get; set; }
        public DbSet<DichVu> DichVus { get; set; }
        public DbSet<HoaDonChi> HoaDonChis { get; set; }
        public DbSet<HoaDonThu> HoaDonThus { get; set; }
        public DbSet<HoiVien> HoiViens { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LoaiDichVu> LoaiDichVus { get; set; }
        public DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public DbSet<NguoiOCung> NguoiOCungs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhanHoi> PhanHois { get; set; }
        public DbSet<Phong> Phongs { get; set; }
        public DbSet<PhongVatTu> PhongVatTus { get; set; }
        public DbSet<SuDungDichVu> SuDungDichVus { get; set; }
        public DbSet<TinhTrangPhong> TinhTrangPhongs { get; set; }
        public DbSet<TrangThaiThuePhong> TrangThaiThuePhongs { get; set; }
        public DbSet<User> UserS { get; set; }
    }
}
