//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiThuePhong
    {
        public TrangThaiThuePhong()
        {
            this.BangThuePhongs = new HashSet<BangThuePhong>();
        }
    
        public int ID { get; set; }
        public string TenTTTP { get; set; }
    
        public virtual ICollection<BangThuePhong> BangThuePhongs { get; set; }
    }
}
